language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danny1977/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run danny1977/react-test npm test -- --coverage
  - docker run -e CI=true danny1977/react-test npm test

after_success:
  - docker build -t danny1977/multi-client ./client
  - docker build -t danny1977/multi-nginx ./nginx
  - docker build -t danny1977/multi-server ./server
  - docker build -t danny1977/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push danny1977/multi-client
  - docker push danny1977/multi-nginx
  - docker push danny1977/multi-server
  - docker push danny1977/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-352992574067
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
